/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_ihmc_affinity_Affinity */

#ifndef _Included_us_ihmc_affinity_Affinity
#define _Included_us_ihmc_affinity_Affinity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_ihmc_affinity_Affinity
 * Method:    setAffinity
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_us_ihmc_affinity_Affinity_setAffinity___3I
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     us_ihmc_affinity_Affinity
 * Method:    setAffinity
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_us_ihmc_affinity_Affinity_setAffinity__J_3I
  (JNIEnv *, jclass, jlong, jintArray);

#ifdef __cplusplus
}
#endif
#endif
