/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_ihmc_process_Scheduler */

#ifndef _Included_us_ihmc_process_Scheduler
#define _Included_us_ihmc_process_Scheduler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_ihmc_process_Scheduler
 * Method:    setScheduler
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_us_ihmc_process_Scheduler_setScheduler
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     us_ihmc_process_Scheduler
 * Method:    getScheduler
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_us_ihmc_process_Scheduler_getScheduler
  (JNIEnv *, jclass, jint);

/*
 * Class:     us_ihmc_process_Scheduler
 * Method:    getPriority
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_us_ihmc_process_Scheduler_getPriority
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
